name: build

on:
  schedule:
    # launch the build weekly to check that everything works find
    - cron:  '0 0 * * 0' 
  push:
    branches:
      - main
      - master

env: # Change this if needed
  Rmarkdown-file: LocalForest.Rmd

jobs:
  build_computorticle:
    name: Build Computo article with Rmarkdown
    runs-on: "macos-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checking out repository for Github action
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - name: Setting up miniconda with specified Python and R dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: computorbuild
          environment-file: environment.yml
          channel-priority: strict
          use-only-tar-bz2: true

      - name: Setup pandoc for Rmarkdown
        uses: r-lib/actions/setup-pandoc@v1 

      - name: Install additional R dependencies
        run: | 
          conda run -n computorbuild Rscript r-addons.R
          
      - name: Rendering Rmd file to HTML
        run: |          
          conda run -n computorbuild Rscript -e 'rmarkdown::render("${{ env.Rmarkdown-file }}", output_file = "index.html", output_dir = "_build")'

      - name: Deploying article on github pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _build
          CLEAN: true
